import React, { useState, useEffect } from "react";

import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    Dimensions,
    NativeModules,
} from "react-native";

import { router } from "expo-router";
import LottieView from "lottie-react-native";
import QRCode from "react-native-qrcode-svg";
import { SafeAreaView } from "react-native-safe-area-context";

import ScreenHeader from "../components/ScreenHeader";

const { width } = Dimensions.get("window");

const { UniCampusHCE } = NativeModules;
const UnicampusHCE = UniCampusHCE;

// Your Lottie file
const NFC_ANIMATION = require("../../assets/animations/6.json");

export default function NfcEidScreen() {
    const [mode, setMode] = useState("nfc");

    // QR generated by the native Android module
    const [qrValue, setQrValue] = useState(null);
    const [qrLoading, setQrLoading] = useState(false);

    // const { UniCampusHCE } = NativeModules;
    // const UnicampusHCE = UniCampusHCE;

    /**
     * Generate a fresh QR using the native Android module.
     */
    const generateQr = async () => {
        try {
            // Make sure the native module exists
            if (!UnicampusHCE) {
                throw new Error(
                    "UnicampusHCE native module is not available"
                );
            }

            if (!UnicampusHCE.generateQr) {
                throw new Error(
                    "generateQr() is not available on UnicampusHCE"
                );
            }

            setQrLoading(true);

            console.log("🔐 Generating secure QR...");

            const qr = await UnicampusHCE.generateQr();

            console.log("🔐 GENERATED QR:", qr);

            if (!qr) {
                throw new Error("Native QR generator returned an empty value");
            }

            setQrValue(qr);
        } catch (error) {
            console.error("❌ QR GENERATION ERROR:", error);

            setQrValue(null);
        } finally {
            setQrLoading(false);
        }
    };

    /**
     * Switch to NFC mode.
     */
    const handleNfcMode = () => {
        setMode("nfc");
    };

    /**
     * Switch to QR mode and generate
     * a fresh QR immediately.
     */
    const handleQrMode = async () => {
        setMode("qr");
        await generateQr();
    };

    return (
        <SafeAreaView style={styles.container}>
            {/* HEADER */}
            <ScreenHeader
                title="NFC e-ID"
                onBackPress={() => router.back()}
                showBackButton={true}
            />

            {/* MAIN CONTENT */}
            <View style={styles.content}>
                {mode === "nfc" ? (
                    <NfcView />
                ) : (
                    <QrView
                        value={qrValue}
                        loading={qrLoading}
                        onRegenerate={generateQr}
                    />
                )}
            </View>

            {/* MODE SWITCHER */}
            <View style={styles.modeContainer}>
                {/* NFC BUTTON */}
                <TouchableOpacity
                    style={[
                        styles.modeButton,
                        mode === "nfc" && styles.activeMode,
                    ]}
                    activeOpacity={0.8}
                    onPress={handleNfcMode}
                >
                    <Text
                        style={[
                            styles.modeText,
                            mode === "nfc" && styles.activeModeText,
                        ]}
                    >
                        NFC
                    </Text>
                </TouchableOpacity>

                {/* QR BUTTON */}
                <TouchableOpacity
                    style={[
                        styles.modeButton,
                        mode === "qr" && styles.activeMode,
                    ]}
                    activeOpacity={0.8}
                    onPress={handleQrMode}
                >
                    <Text
                        style={[
                            styles.modeText,
                            mode === "qr" && styles.activeModeText,
                        ]}
                    >
                        QR
                    </Text>
                </TouchableOpacity>
            </View>
        </SafeAreaView>
    );
}

/* ------------------------------------------------ */
/* NFC VIEW */
/* ------------------------------------------------ */

// function NfcView() {
//     return (
//         <View style={styles.nfcView}>
//             <View style={styles.animationContainer}>
//                 <LottieView
//                     source={NFC_ANIMATION}
//                     autoPlay
//                     loop
//                     style={styles.nfcAnimation}
//                 />
//             </View>

//             <View style={styles.statusContainer}>
//                 <Text style={styles.statusTitle}>
//                     Working in background
//                 </Text>

//                 <Text style={styles.statusSubtitle}>
//                     No internet required
//                 </Text>
//             </View>
//         </View>
//     );
// }

function NfcView() {

    const [hceAvailable, setHceAvailable] = useState(null);
    const [nfcEnabled, setNfcEnabled] = useState(null);
    const [checking, setChecking] = useState(true);

    useEffect(() => {
        checkNfcStatus();
    }, []);

    const checkNfcStatus = async () => {

        try {

            setChecking(true);

            console.log("🔍 Checking HCE support...");

            const hasHce = await UniCampusHCE.hasHce();

            console.log("📱 HCE available:", hasHce);

            setHceAvailable(hasHce);

            // If device doesn't support HCE,
            // there is no need to check NFC state.
            if (!hasHce) {
                setNfcEnabled(false);
                return;
            }

            console.log("🔍 Checking NFC status...");

            const enabled = await UniCampusHCE.isNfcEnabled();

            console.log("📡 NFC enabled:", enabled);

            setNfcEnabled(enabled);

        } catch (error) {

            console.error(
                "❌ NFC STATUS CHECK ERROR:",
                error
            );

            // Fail safely into QR fallback
            setHceAvailable(false);
            setNfcEnabled(false);

        } finally {

            setChecking(false);

        }
    };


    // --------------------------------
    // CHECKING
    // --------------------------------

    if (checking) {

        return (
            <View style={styles.nfcView}>

                <View style={styles.animationContainer}>

                    <LottieView
                        source={NFC_ANIMATION}
                        autoPlay
                        loop
                        style={styles.nfcAnimation}
                    />

                </View>

                <View style={styles.statusContainer}>

                    <Text style={styles.statusTitle}>
                        Checking NFC
                    </Text>

                    <Text style={styles.statusSubtitle}>
                        Checking device capabilities...
                    </Text>

                </View>

            </View>
        );
    }


    // --------------------------------
    // NO HCE
    // --------------------------------

    if (hceAvailable === false) {

        return (
            <View style={styles.nfcView}>

                <View style={styles.animationContainer}>

                    {/* You can replace this with
                        your QR fallback image/Lottie */}
                    <Text style={styles.fallbackIcon}>
                        QR
                    </Text>

                </View>

                <View style={styles.statusContainer}>

                    <Text style={styles.statusTitle}>
                        NFC ID unavailable
                    </Text>

                    <Text style={styles.statusSubtitle}>
                        This device does not support Host Card Emulation.
                        Use the QR fallback to access your digital ID.
                    </Text>

                </View>

            </View>
        );
    }


    // --------------------------------
    // HCE EXISTS BUT NFC IS OFF
    // --------------------------------

    if (hceAvailable === true && nfcEnabled === false) {

        return (
            <View style={styles.nfcView}>

                <View style={styles.animationContainer}>

                    {/* Replace this with your
                        enable-NFC Lottie/image */}
                    <Text style={styles.nfcOffIcon}>
                        NFC
                    </Text>

                </View>

                <View style={styles.statusContainer}>

                    <Text style={styles.statusTitle}>
                        Enable NFC
                    </Text>

                    <Text style={styles.statusSubtitle}>
                        NFC is currently disabled. Turn on NFC in your
                        device settings to use your digital ID.
                    </Text>

                </View>

            </View>
        );
    }


    // --------------------------------
    // HCE + NFC ENABLED
    // --------------------------------

    return (

        <View style={styles.nfcView}>

            <View style={styles.animationContainer}>

                <LottieView
                    source={NFC_ANIMATION}
                    autoPlay
                    loop
                    style={styles.nfcAnimation}
                />

            </View>

            <View style={styles.statusContainer}>

                <Text style={styles.statusTitle}>
                    Working in background
                </Text>

                <Text style={styles.statusSubtitle}>
                    No internet required
                </Text>

            </View>

        </View>
    );
}

/* ------------------------------------------------ */
/* QR VIEW */
/* ------------------------------------------------ */

function QrView({ value, loading, onRegenerate }) {
    const [timeLeft, setTimeLeft] = useState(1 * 60);

    /**
     * Countdown timer.
     *
     * The QR is valid for 5 minutes.
     */
    useEffect(() => {
        if (timeLeft <= 0) {
            return;
        }

        const interval = setInterval(() => {
            setTimeLeft((prev) => {
                if (prev <= 1) {
                    clearInterval(interval);
                    return 0;
                }

                return prev - 1;
            });
        }, 1000);

        return () => clearInterval(interval);
    }, [timeLeft]);

    /**
     * When the QR expires, generate a new one.
     */
    useEffect(() => {
        if (timeLeft === 0 && !loading) {
            console.log("⏰ QR expired");

            onRegenerate();

            // Reset countdown
            setTimeLeft(1 * 60);
        }
    }, [timeLeft, loading]);

    const minutes = Math.floor(timeLeft / 60)
        .toString()
        .padStart(2, "0");

    const seconds = (timeLeft % 60)
        .toString()
        .padStart(2, "0");

    return (
        <View style={styles.qrView}>
            {/* TITLE */}
            <Text style={styles.qrTitle}>
                Scan to verify
            </Text>

            {/* DESCRIPTION */}
            <Text style={styles.qrSubtitle}>
                Present this code to a UniCampus reader
            </Text>

            {/* EXPIRY */}
            <Text style={styles.qrExpiry}>
                Expires in{" "}
                <Text style={styles.timer}>
                    {minutes}:{seconds}
                </Text>
            </Text>

            {/* QR CONTAINER */}
            <View style={styles.qrContainer}>
                {loading ? (
                    <View style={styles.qrPlaceholder}>
                        <Text style={styles.qrLoading}>
                            Generating secure QR...
                        </Text>
                    </View>
                ) : value ? (
                    <QRCode
                        value={value}
                        size={width * 0.62}
                        color="#000000"
                        backgroundColor="#FFFFFF"
                        quietZone={18}
                    />
                ) : (
                    <View style={styles.qrPlaceholder}>
                        <Text style={styles.qrLoading}>
                            Unable to generate QR
                        </Text>

                        <TouchableOpacity
                            style={styles.retryButton}
                            activeOpacity={0.8}
                            onPress={onRegenerate}
                        >
                            <Text style={styles.retryText}>
                                Try again
                            </Text>
                        </TouchableOpacity>
                    </View>
                )}
            </View>

            {/* HINT */}
            <Text style={styles.qrHint}>
                Keep your screen steady while scanning
            </Text>
        </View>
    );
}

/* ------------------------------------------------ */
/* STYLES */
/* ------------------------------------------------ */

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFFFFF",
    },

    /* ------------------------------------------------ */
    /* HEADER */
    /* ------------------------------------------------ */

    header: {
        height: 64,
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },

    backButton: {
        width: 42,
        height: 42,
        alignItems: "flex-start",
        justifyContent: "center",
    },

    backIcon: {
        fontSize: 34,
        fontWeight: "300",
        color: "#222222",
        lineHeight: 38,
    },

    headerTitle: {
        position: "absolute",
        left: 0,
        right: 0,
        textAlign: "center",
        fontSize: 17,
        fontWeight: "600",
        color: "#222222",
    },

    moreButton: {
        width: 42,
        height: 42,
        alignItems: "flex-end",
        justifyContent: "center",
    },

    moreIcon: {
        fontSize: 16,
        letterSpacing: 2,
        color: "#222222",
    },

    /* ------------------------------------------------ */
    /* CONTENT */
    /* ------------------------------------------------ */

    content: {
        flex: 1,
        paddingHorizontal: 20,
    },

    /* ------------------------------------------------ */
    /* NFC */
    /* ------------------------------------------------ */

    nfcView: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },

    animationContainer: {
        width: width * 0.72,
        height: width * 0.72,
        alignItems: "center",
        justifyContent: "center",
        marginTop: -35,
    },

    nfcAnimation: {
        width: "100%",
        height: "100%",
    },

    statusContainer: {
        alignItems: "center",
        marginTop: 12,
    },

    statusTitle: {
        fontSize: 15,
        fontWeight: "500",
        color: "#252525",
    },

    statusSubtitle: {
        marginTop: 5,
        fontSize: 14,
        fontWeight: "400",
        color: "#777777",
    },

    /* ------------------------------------------------ */
    /* QR */
    /* ------------------------------------------------ */

    qrView: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingBottom: 30,
    },

    qrTitle: {
        fontSize: 21,
        fontWeight: "600",
        color: "#202020",
        marginBottom: 7,
    },

    qrSubtitle: {
        fontSize: 14,
        color: "#777777",
        textAlign: "center",
        marginBottom: 28,
        paddingHorizontal: 25,
    },

    qrExpiry: {
        fontSize: 14,
        color: "#777777",
        textAlign: "center",
        marginBottom: 28,
    },

    timer: {
        fontSize: 14,
        fontWeight: "600",
        color: "#E53935",
    },

    qrContainer: {
        padding: 18,
        backgroundColor: "#FFFFFF",
        borderRadius: 20,

        // Very subtle elevation
        shadowColor: "#000000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.08,
        shadowRadius: 12,

        elevation: 3,
    },

    qrPlaceholder: {
        width: width * 0.62,
        height: width * 0.62,
        alignItems: "center",
        justifyContent: "center",
    },

    qrLoading: {
        fontSize: 14,
        color: "#777777",
        textAlign: "center",
    },

    retryButton: {
        marginTop: 14,
        paddingVertical: 9,
        paddingHorizontal: 18,
        borderRadius: 20,
        backgroundColor: "#2E8B3A",
    },

    retryText: {
        color: "#FFFFFF",
        fontSize: 13,
        fontWeight: "600",
    },

    qrHint: {
        marginTop: 24,
        fontSize: 13,
        color: "#8A8A8A",
        textAlign: "center",
    },

    /* ------------------------------------------------ */
    /* MODE SWITCHER */
    /* ------------------------------------------------ */

    modeContainer: {
        flexDirection: "row",
        alignSelf: "center",
        backgroundColor: "#F2F2F2",
        borderRadius: 30,
        padding: 4,
        marginBottom: 18,
    },

    modeButton: {
        minWidth: 95,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 24,
        alignItems: "center",
        justifyContent: "center",
    },

    activeMode: {
        backgroundColor: "#2E8B3A",
    },

    modeText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#777777",
    },

    activeModeText: {
        color: "#FFFFFF",
    },
});